### PR TITLE
refactor: using sourcemap as sourcemap builder

### PR DESCRIPTION
**Pull request by underfin**
The pr using [`sourcemap`](https://github.com/getsentry/rust-sourcemap) as sourcemap builder. It will avoid some issue at rolldown.
1. avoid different `sourcemap` crate and struct to cast.
2. avoid return `DecodedMap`, because we need to encode vlq mapping to remapping.

### CODE REVIEW

**Review by hyf0 — APPROVED** [review]

**Review by hyf0 — DISMISSED** [review]

**Comment by underfin** [comment]
@hyf0 Could you merge this and publish a version?

**Comment by underfin** [comment]
@hyf0 Could you merge this and publish a version?

**Comment by underfin** [comment]
I need it to creat mapping to same as `magicString.generateMap({ hires: true, includeContent: true, source: id });`

**Comment by underfin** [comment]
Please wait publish version, i need to using oxc sourcemap

**Pull request merged**
